---
- name: Install Tomcat without sudo
  hosts: localhost
  vars:
    tomcat_version: "9.0.62"
    tomcat_install_dir: "{{ ansible_env.HOME }}/tomcat"
    tomcat_user: "{{ ansible_user }}"
  tasks:
    - name: Create Tomcat directory
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        mode: '0755'

    - name: Download Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        validate_certs: yes

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        creates: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Update Tomcat permissions
      file:
        path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_user }}"
        recurse: yes
        mode: '0755'

    - name: Set CATALINA_HOME environment variable
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "export CATALINA_HOME={{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        create: yes
