---
- name: Install Tomcat without sudo
  hosts: localhost
  vars:
    tomcat_version: "9.0.62"
    tomcat_install_dir: "{{ ansible_env.HOME }}/tomcat"
    tomcat_user: "{{ ansible_user }}"
  tasks:


    - name: Set CATALINA_HOME environment variable
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "export CATALINA_HOME={{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
        create: yes
