---
- name: Install, Deploy, and Restart Tomcat
  hosts: tomcatsrv
  become: yes
  vars:
    tomcat_version: "9.0.62"
    tomcat_home: "/mnt/d/ansible-example/tomcat/apache-tomcat-9.0.85"
    war_file: "sparkjava-hello-world-1.0.war" 
    app_name: "myapp"

  tasks:


    - name: Stop Tomcat
      command: "{{ tomcat_home }}/bin/shutdown.sh"
      ignore_errors: yes
    
    - name: Deploy WAR file
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_home }}/webapps/{{ app_name }}.war"
 

    - name: Start Tomcat
      command: "{{ tomcat_home }}/bin/startup.sh"
      async: 60
      poll: 0
