---
- name: Install, Deploy, and Restart Tomcat
  hosts: tomcatsrv
  become: yes
  vars:
    tomcat_version: "9.0.62"
    tomcat_home: "tomcat"
    war_file: "demo-0.0.1-SNAPSHOT.war" 
    app_name: "demo-0.0.1-SNAPSHOT"

  tasks:
   
    - name: Install Java JDK
      ansible.builtin.apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
        dest: /tmp/apache-tomcat-9.0.85.tar.gz

    - name: Create Tomcat Directory
      ansible.builtin.file:
        path: "{{ tomcat_home }}"
        state: directory

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-9.0.85.tar.gz
        dest: "{{ tomcat_home }}"
        remote_src: yes

    - name: Stop Tomcat
      command: "{{ tomcat_home }}/apache-tomcat-9.0.85/bin/shutdown.sh"
      ignore_errors: yes
    
    - name: Deploy WAR file
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_home }}/apache-tomcat-9.0.85/webapps/{{ app_name }}.war"
 
    - name: Start Tomcat
      command: "nohup {{ tomcat_home }}apache-tomcat-9.0.85/bin/startup.sh"
      async: 60
      poll: 0
