---
- name: Install, Deploy, and Restart Tomcat
  hosts: localhost
  become: yes
  vars:
    tomcat_version: "9.0.62"
    tomcat_home: "/mnt/d/ansible-example/tomcat/apache-tomcat-9.0.85"
    war_file: "../sparkjava-hello-world-1.0.war" 
    app_name: "sparkjava-hello-world-1.0"

  tasks:
   
    - name: Install Java JDK
      ansible.builtin.apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
        dest: /tmp/apache-tomcat-9.0.85.tar.gz

    - name: Create Tomcat Directory
      ansible.builtin.file:
        path: tomcat
        state: directory

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-9.0.85.tar.gz
        dest: tomcat
        remote_src: yes

    - name: Stop Tomcat
      command: "{{ tomcat_home }}/bin/shutdown.sh"
      ignore_errors: yes
    
    - name: Deploy WAR file
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_home }}/webapps/{{ app_name }}.war"
 
    - name: Start Tomcat
      command: "{{ tomcat_home }}/bin/startup.sh"
      async: 60
      poll: 0
