---
- name: Manage Tomcat as a service with Ansible
  hosts: tomcatsrv
  become: yes
  vars:
    tomcat_version: "9.0.62"
    tomcat_home: "/opt/tomcat"
    war_file: "demo-0.0.1-SNAPSHOT.war"
    app_name: "demo-0.0.1-SNAPSHOT"
    java_home: "/usr/lib/jvm/java-11-openjdk"


  tasks:
    - name: Create Tomcat Directory
      ansible.builtin.file:
        path: "{{ tomcat_home }}"
        state: directory

    - name: Download Tomcat
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
        dest: /tmp/apache-tomcat-9.0.85.tar.gz

    - name: Extract Tomcat
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-9.0.85.tar.gz
        dest: "{{ tomcat_home }}"
        remote_src: yes

    - name: Create Tomcat systemd service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          Environment=CATALINA_PID={{ tomcat_home }}/apache-tomcat-9.0.85/temp/tomcat.pid
          Environment=CATALINA_HOME={{ tomcat_home }}/apache-tomcat-9.0.85
          Environment=CATALINA_BASE={{ tomcat_home }}/apache-tomcat-9.0.85
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

          ExecStart="{{ tomcat_home }}/apache-tomcat-9.0.85/bin/startup.sh"
          ExecStop="{{ tomcat_home }}/apache-tomcat-9.0.85/bin/shutdown.sh"

          owner=tomcat
          Group=tomcat
          mode=0777

          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Restart tomcat

    - name: Enable and start Tomcat service
      systemd:
        name: tomcat
        enabled: yes
        state: started

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart tomcat
      systemd:
        name: tomcat
        state: restarted
