name: CI-CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  build:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
          cache: maven

      - name: Build and analyze
        run: mvn -B clean package

      - name: publish
        run: mvn deploy -Dmaven.install.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: copy
        run: cp  target/*.war ansible

      - uses: actions/upload-artifact@v4
        with:
          name: my-application
          path: ansible
          retention-days: 5
      
      - name: Output artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
  deploy:
    needs: build
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    runs-on: self-hosted
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-application  

      - name: Display structure of downloaded files
        run: ls -ltr
    
        
      - name: Run ansible script
        shell: bash  
        run: |
            hostname -i
            whoami 
            cd ansible
            ansible-playbook -i webhost.ini tomcat.yml -vvv
            